version: "3"
services:
  node:
    image: "node:8.6.0"
    user: "node"
    working_dir: "/home/node/app"
    environment:
      - NODE_ENV=development
    volumes:
      -  ./:/home/node/app
    ports:
      - "3000:3000"
    #command: "npm start"
    command: "node_modules/.bin/nodemon -L --exec npm start" # faz com que o node se auto recarregue com qualquer mudança de codigo

  mongo:
    image: "mongo:3.4.9"
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"        