version: "3"
services:
  node:
    image: "node:8.6.0"
    user: "node"
    working_dir: "/home/node/app"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/email_marketing
    volumes:
      -  ./:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
  sendmail:
    image: "node:8.6.0"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: "node bin/send_email_service.js"

  mongo:
    image: "mongo:3.4.9"
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"        

